BTC:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
      private_key_path: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      threads: 1
