services:
  dbt:
    build:
      context: ../..
      dockerfile: .devcontainer/dbt/Dockerfile
    volumes:
      - ../..:/workspaces/dbt-tutorial-BIT:cached
      - ${HOME}/.dbt:/root/.dbt-host:ro
      - ${HOME}/.ssh:/root/.ssh:ro
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    command: sleep infinity
